clusterRole:
  rules:
    - apiGroups: [""]
      resources:
        [
          "pods",
          "namespaces",
          "nodes",
          "resourcequotas",
          "replicationcontrollers",
          "services",
          "nodes/metrics",
          "nodes/stats",
          "nodes/proxy",
          "events",
          "endpoints",
        ]
      verbs: ["get", "watch", "list"]
    - apiGroups: ["apps"]
      resources: ["replicasets", "daemonsets", "deployments", "statefulsets"]
      verbs: ["get", "list", "watch"]
    - apiGroups: ["extensions"]
      resources: ["replicasets"]
      verbs: ["get", "list", "watch"]
    - apiGroups: ["batch"]
      resources: ["cronjobs", "jobs"]
      verbs: ["get", "list", "watch"]
    - apiGroups: ["autoscaling"]
      resources: ["horizontalpodautoscalers"]
      verbs: ["get", "list", "watch"]
