nameOverride: mimir

fullnameOverride: mimir

image:
  repository: grafana/mimir
  tag: r335-39405cd
  pullPolicy: IfNotPresent

global:
  # -- Definitions to set up nginx resolver
  dnsService: kube-dns
  dnsNamespace: kube-system
  clusterDomain: cluster.local.

serviceAccount:
  create: true
  name: ${service_account_name}
  annotations:
    eks.amazonaws.com/role-arn: ${role_arn}

mimir:
  structuredConfig:
    enable_go_runtime_metrics: true
    multitenancy_enabled: true
    usage_stats:
      enabled: false
      installation_mode: helm
    blocks_storage:
      backend: s3
      s3:
        bucket_name: ${mimir_chunks_bucket}
        insecure: false
        endpoint: s3.ap-south-2.amazonaws.com
    frontend:
      log_queries_longer_than: 10s
      grpc_client_config:
        grpc_compression: snappy
    store_gateway:
      sharding_ring:
        replication_factor: 1
    ingester:
      instance_limits:
        max_ingestion_rate: 0
      ring:
        replication_factor: 1
        final_sleep: 0s
        num_tokens: 512
    ingester_client:
      grpc_client_config:
        grpc_compression: snappy
        max_recv_msg_size: 104857600
        max_send_msg_size: 104857600
    server:
      log_level: warn
      grpc_server_max_concurrent_streams: 1000
      grpc_server_max_recv_msg_size: 104857600
      grpc_server_max_send_msg_size: 104857600
    limits:
      ingestion_rate: 80000
      max_global_series_per_metric: 0
      max_global_series_per_user: 0
      max_label_names_per_series: 100
      align_queries_with_step: true
      compactor_blocks_retention_period: 3h
    memberlist:
      abort_if_cluster_join_fails: false
      compression_enabled: true
    ruler:
      query_frontend:
        grpc_client_config:
          grpc_compression: snappy
    query_scheduler:
      grpc_client_config:
        grpc_compression: snappy
    alertmanager:
      alertmanager_client:
        grpc_compression: snappy

alertmanager:
  enabled: false
  zoneAwareReplication:
    enabled: false
  resources:
    requests:
      cpu: 20m
  persistentVolume:
    enabled: true
    name: storage
    storageClass: obsrv-sc
    size: 10Gi
  # extraVolumes:
  #   - name: otel-ca-volume
  #     configMap:
  #       name: otel-collector-ca
  #       items:
  #         - key: ca.crt
  #           path: ca.crt
  # extraVolumeMounts:
  #   - name: otel-ca-volume
  #     mountPath: /etc/otel/certs
  #     readOnly: true

compactor:
  persistentVolume:
    enabled: true
    name: storage
    storageClass: obsrv-sc
    size: 10Gi
    enableRetentionPolicy: false
    whenDeleted: Delete
  resources:
    requests:
      cpu: 20m

distributor:
  resources:
    requests:
      cpu: 20m

ingester:
  replicas: 2
  persistentVolume:
    enabled: true
    name: storage
    storageClass: obsrv-sc
    size: 10Gi
    whenDeleted: Delete
  zoneAwareReplication:
    enabled: false
  resources:
    requests:
      cpu: 20m

overrides_exporter:
  resources:
    requests:
      cpu: 20m

querier:
  replicas: 1
  resources:
    requests:
      cpu: 20m

query_frontend:
  resources:
    requests:
      cpu: 20m

query_scheduler:
  replicas: 1
  resources:
    requests:
      cpu: 20m

ruler:
  resources:
    requests:
      cpu: 20m

store_gateway:
  persistentVolume:
    enabled: true
    name: storage
    storageClass: obsrv-sc
    size: 10Gi
    whenDeleted: Delete
  replicas: 2
  zoneAwareReplication:
    enabled: false
  resources:
    requests:
      cpu: 20m

rollout_operator:
  resources:
    requests:
      cpu: 20m

minio:
  enabled: false

monitoring:
  # Dashboards for monitoring Loki
  dashboards:
    # -- If enabled, create configmap with dashboards for monitoring Loki
    enabled: false
    # -- Alternative namespace to create dashboards ConfigMap in
    namespace: null
    # -- Additional annotations for the dashboards ConfigMap
    annotations: {}
    # -- Labels for the dashboards ConfigMap
    labels:
      grafana_dashboard: "1"
  # -- Recording rules for monitoring Loki, required for some dashboards
  rules:
    # -- If enabled, create PrometheusRule resources with Loki recording rules
    enabled: false

    configs:
      LokiRequestErrors:
        enabled: true
        for: 15m
        lookbackPeriod: 2m
        severity: critical
        threshold: 10
      LokiRequestPanics:
        enabled: true
        lookbackPeriod: 10m
        severity: critical
        threshold: 0
      LokiRequestLatency:
        enabled: true
        for: 15m
        severity: critical
        threshold: 1
      LokiTooManyCompactorsRunning:
        enabled: true
        for: 5m
        severity: warning
      LokiCanaryLatency:
        enabled: true
        for: 15m
        lookbackPeriod: 5m
        severity: warning
        threshold: 5

    # -- Alternative namespace to create PrometheusRule resources in
    namespace: null
    # -- Additional annotations for the rules PrometheusRule resource
    annotations: {}
    # -- Additional labels for the rules PrometheusRule resource
    labels: {}
    # -- Additional annotations for PrometheusRule alerts
    additionalRuleAnnotations: {}
    # e.g.:
    # additionalRuleAnnotations:
    #   runbook_url: "https://runbooks.example.com/oncall/loki"
    #   summary: "What this alert means and how to respond"
    # -- Additional labels for PrometheusRule alerts
    additionalRuleLabels: {}
    # -- Additional groups to add to the rules file
    additionalGroups: []
    # - name: additional-loki-rules
    #   rules:
    #     - record: job:loki_request_duration_seconds_bucket:sum_rate
    #       expr: sum(rate(loki_request_duration_seconds_bucket[1m])) by (le, job)
    #     - record: job_route:loki_request_duration_seconds_bucket:sum_rate
    #       expr: sum(rate(loki_request_duration_seconds_bucket[1m])) by (le, job, route)
    #     - record: node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate
    #       expr: sum(rate(container_cpu_usage_seconds_total[1m])) by (node, namespace, pod, container)
  # -- ServiceMonitor configuration
  serviceMonitor:
    # -- If enabled, ServiceMonitor resources for Prometheus Operator are created
    enabled: false
    # -- To disable setting a 'cluster' label in metrics, set to 'null'.
    # To overwrite the 'cluster' label with your own value, set to a non-empty string.
    # Keep empty string "" to have the default value in the 'cluster' label, which is the helm release name for Loki.
    clusterLabel: ""
    # -- Namespace selector for ServiceMonitor resources
    namespaceSelector: {}
    # -- ServiceMonitor annotations
    annotations: {}
    # -- Additional ServiceMonitor labels
    labels: {}
    # -- ServiceMonitor scrape interval
    # Default is 15s because included recording rules use a 1m rate, and scrape interval needs to be at
    # least 1/4 rate interval.
    interval: 15s
    # -- ServiceMonitor scrape timeout in Go duration format (e.g. 15s)
    scrapeTimeout: null
    # -- ServiceMonitor relabel configs to apply to samples before scraping
    # https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#relabelconfig
    relabelings: []
    # -- ServiceMonitor metric relabel configs to apply to samples before ingestion
    # https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#endpoint
    metricRelabelings: []
    # -- ServiceMonitor will use http by default, but you can pick https as well
    scheme: http
    # -- ServiceMonitor will use these tlsConfig settings to make the health check requests
    tlsConfig: null
    # -- ServiceMonitor job label prefix will be used to generate the job label for the scraped metrics.
    # -- The job label is required for the included dashboards to work.
    jobPrefix: '{{ include "loki.namespace" $ }}/'

# -- DEPRECATED Configuration for the table-manager. The table-manager is only necessary when using a deprecated
# index type such as Cassandra, Bigtable, or DynamoDB, it has not been necessary since loki introduced self-
# contained index types like 'boltdb-shipper' and 'tsdb'. This will be removed in a future helm chart.
