apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: otel-collector-ingress
  namespace: opentelemetry-collector
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocal: "GRPC"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: otel.${meda_domain_name}
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: opentelemetry-collector
                port:
                  number: 4317
