apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-ta-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otel-ta-role
subjects:
  - kind: ServiceAccount
    name: otel-ta-sa
    namespace: meta-monitoring
