apiVersion: v1
kind: Pod
metadata:
  name: newlocation
spec:
  containers:
    - name: count
      image: busybox:1.28
      args:
        - /bin/sh
        - -c
        - >
          i=0;
          while true;
          do
            echo "$i: $(date)" >> /myapp/test/mysexyapp/go/1.log;
            echo "$(date) INFO $i" >> /myapp/test/mysexyapp/go/2.log;
            i=$((i+1));
            sleep 1;
          done
      volumeMounts:
        - name: testlog
          mountPath: /myapp/test/mysexyapp/go
    - name: count-log-1
      image: busybox:1.28
      args: [/bin/sh, -c, "tail -n+1 -F /myapp/test/mysexyapp/go/1.log"]
      volumeMounts:
        - name: testlog
          mountPath: /myapp/test/mysexyapp/go
    - name: count-log-2
      image: busybox:1.28
      args: [/bin/sh, -c, "tail -n+1 -F /myapp/test/mysexyapp/go/2.log"]
      volumeMounts:
        - name: testlog
          mountPath: /myapp/test/mysexyapp/go
  volumes:
    - name: testlog
      emptyDir: {}
