apiVersion: v1
kind: Pod
metadata:
  name: alpine
  namespace: default
spec:
  containers:
    - image: chentex/random-logger
      command:
        - /bin/sh
        - "-c"
        - "sleep 60m"
      imagePullPolicy: IfNotPresent
      name: alpine
  restartPolicy: Always
