apiVersion: v1
kind: Pod
metadata:
  name: log-test-pod
  labels:
    app: log-test
spec:
  containers:
    # 1. Container logging to a custom file path (won't be picked up by filelog)
    - name: custom-log-writer
      image: busybox:latest
      command: ["/bin/sh", "-c"]
      args:
        - |
          mkdir -p /app/logs;
          i=0;
          while true; do
            echo "$(date -u +"%Y-%m-%dT%H:%M:%S.%NZ") [INFO] Custom file log message $i" >> /app/logs/output.log;
            echo "$(date -u +"%Y-%m-%dT%H:%M:%S.%NZ") [DEBUG] Also writing a debug message to custom file $i" >> /app/logs/output.log;
            i=$((i+1));
            sleep 10;
          done
      volumeMounts:
        - name: app-log-volume
          mountPath: /app/logs
  volumes:
    - name: app-log-volume
