apiVersion: v1
kind: PersistentVolume
metadata:
  name: dctm-logs-pv-meta-monitoring
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-075172fd8351b4948  # Same volume as the original one
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dctm-logs-pvc
  namespace: meta-monitoring
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 10Gi
  volumeName: dctm-logs-pv-meta-monitoring  # The new PV
