name: EKS-With-Terraform Destroy
on: workflow_dispatch
run-name: "Argus Destroy by ${{ github.actor }},through ${{ github.event_name }}"
permissions:
  contents: read
jobs:
  delete_eks_stack:
    name: "Delete EKS Stack"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./_1_eks
    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-2

      - name: Test configuration of AWS CLI
        run: |
          aws --version
          aws configure list | grep region | awk '{print $2}'

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.4.4

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        id: fmt
        run: terraform fmt -check=true
        continue-on-error: true

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -auto-approve -no-color -input=false
